name = "rolldorado-app-com-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldorado-app.com.pt"
HMAC_KEY = "39d95ec82d88740d47b2d931bade5f68ea2e12897af99c559ecfc18694e62bf8"
COOKIE_NAME = "sux"
PLAY_PATH = "discover"
BUTTON_ID = "pc2983b6078c2a788d3a3ec407c0e75c2"
GATE_SALT = "304b7837b1aba316"
